from __future__ import annotations


DASHBOARD_MODULE_KEYS = (
    "credit_stress",
    "rate_pressure",
    "real_yield_pressure",
    "inflation_energy_pressure",
    "equity_trend",
    "breadth_concentration_proxy",
    "market_stress_derived",
    "portfolio_deviation",
)
DERIVED_METRIC_KEYS = {
    "dgs10_5d_avg",
    "dgs30_distance_to_5pct",
    "dgs30_breakout_confirmed",
    "sp500_30d_return",
    "sp500_60d_return",
    "nasdaq100_30d_return",
    "nasdaq100_60d_return",
    "nasdaq_vs_sp500_30d",
    "wti_30d_change",
    "brent_30d_change",
    "spy_proxy_30d_return",
    "spy_proxy_60d_return",
    "rsp_proxy_30d_return",
    "rsp_proxy_60d_return",
    "qqq_proxy_30d_return",
    "qqq_proxy_60d_return",
    "spy_vs_rsp_30d",
    "spy_vs_rsp_60d",
    "qqq_vs_spy_30d",
    "qqq_vs_spy_60d",
    "hyg_vs_lqd_30d",
    "hyg_vs_lqd_60d",
    "sp500_drawdown_3m",
    "sp500_drawdown_6m",
    "nasdaq100_drawdown_3m",
    "nasdaq100_drawdown_6m",
    "dgs10_dgs2_curve_slope",
    "dgs30_dgs10_curve_slope",
    "tlt_proxy_30d_return",
    "gld_proxy_30d_return",
    "shy_proxy_30d_return",
    "tlt_vs_shy_30d",
    "unemployment_rate_3m_avg",
    "unemployment_rate_12m_low_gap",
    "initial_claims_4w_avg",
    "continuing_claims_4w_avg",
    "sahm_rule_proxy_status",
    "labor_deterioration_status",
    "financial_stress_score",
    "financial_stress_status",
    "financial_stress_dominant_pressure_source",
    "financial_stress_component_contributions",
    "financial_stress_missing_inputs",
    "financial_stress_interpretation_boundary",
    "financial_stress_percentile_context",
    "financial_stress_funding_liquidity_context",
    "pullback_classification",
    "pullback_checklist_items",
    "pullback_missing_critical_inputs",
    "pullback_supporting_evidence",
    "pullback_interpretation_boundary",
    "pullback_percentile_context",
    "pullback_liquidity_funding_context",
    "sofr_effr_spread",
    "effr_iorb_spread",
    "cp_effr_spread",
    "cp_sofr_spread",
    "policy_plumbing_status",
    "short_term_funding_pressure_status",
    "official_stress_reference_status",
    "liquidity_funding_stress_status",
    "liquidity_funding_interpretation_boundary",
    "growth_macro_status",
    "growth_macro_supporting_evidence",
    "growth_macro_missing_inputs",
    "growth_macro_interpretation_boundary",
    "inflation_macro_status",
    "inflation_macro_supporting_evidence",
    "inflation_macro_missing_inputs",
    "inflation_macro_interpretation_boundary",
    "policy_constraint_status",
    "policy_constraint_supporting_evidence",
    "policy_constraint_missing_inputs",
    "policy_constraint_interpretation_boundary",
    "stagflation_watch_status",
    "stagflation_watch_supporting_evidence",
    "stagflation_watch_missing_inputs",
    "stagflation_watch_interpretation_boundary",
    "growth_inflation_macro_pack_model_version",
    "growth_inflation_macro_pack_formula_version",
    "growth_inflation_macro_pack_as_of_date",
    "valuation_context_status",
    "valuation_pressure_hint",
    "valuation_metric_source_quality",
    "valuation_missing_inputs",
    "valuation_interpretation_boundary",
    "earnings_context_status",
    "earnings_missing_inputs",
    "earnings_interpretation_boundary",
    "equity_structure_status",
    "equity_structure_supporting_evidence",
    "equity_structure_missing_inputs",
    "equity_structure_interpretation_boundary",
    "breadth_concentration_context_status",
    "breadth_concentration_supporting_evidence",
    "breadth_concentration_missing_inputs",
    "breadth_concentration_interpretation_boundary",
    "valuation_equity_structure_model_version",
    "valuation_equity_structure_formula_version",
    "valuation_equity_structure_as_of_date",
    "macro_regime_label",
    "support_band",
    "evidence_quality_band",
    "conflict_band",
    "primary_pressure_ranking",
    "supporting_evidence",
    "conflicting_evidence",
    "missing_inputs",
    "blocked_inputs",
    "interpretation_boundary",
    "model_version",
    "formula_version",
    "as_of_date",
    "historical_validation_status",
    "historical_validation_event_count",
    "historical_validation_available_event_count",
    "historical_validation_insufficient_history_event_count",
    "historical_validation_ordinary_pullback_over_escalation_count",
    "historical_validation_stress_window_under_escalation_count",
    "historical_validation_boundary_violation_count",
    "historical_validation_event_window_summary",
    "historical_validation_privacy_flags",
    "historical_validation_validation_boundary",
    "historical_validation_model_version",
    "historical_validation_formula_version",
    "historical_validation_as_of_date",
    "historical_validation_coverage_summary",
    "historical_validation_module_consistency_summary",
    "historical_validation_proxy_constraint_summary",
    "historical_validation_missing_data_summary",
    "historical_validation_replay_version",
    "scenario_stress_status",
    "scenario_stress_scenario_count",
    "scenario_stress_scenarios",
    "scenario_stress_primary_scenario",
    "scenario_stress_affected_groups",
    "scenario_stress_transmission_channels",
    "scenario_stress_severity_band",
    "scenario_stress_uncertainty_band",
    "scenario_stress_supporting_evidence",
    "scenario_stress_missing_inputs",
    "scenario_stress_interpretation_boundary",
    "scenario_stress_model_version",
    "scenario_stress_formula_version",
    "scenario_stress_as_of_date",
    "portfolio_exposure_overlay_status",
    "portfolio_exposure_channel_summary",
    "portfolio_exposure_primary_channels",
    "portfolio_exposure_supporting_evidence",
    "portfolio_exposure_missing_inputs",
    "portfolio_exposure_private_input_policy",
    "portfolio_exposure_interpretation_boundary",
    "portfolio_exposure_model_version",
    "portfolio_exposure_formula_version",
    "portfolio_exposure_as_of_date",
    "portfolio_exposure_equity_beta_context",
    "portfolio_exposure_rates_duration_context",
    "portfolio_exposure_credit_context",
    "portfolio_exposure_liquidity_context",
    "portfolio_exposure_inflation_energy_context",
    "portfolio_exposure_concentration_context",
    "portfolio_exposure_valuation_context",
    "portfolio_exposure_cash_buffer_context",
    "high_yield_spread_percentile",
    "high_yield_spread_zscore",
    "high_yield_spread_robust_zscore",
    "investment_grade_spread_percentile",
    "investment_grade_spread_zscore",
    "investment_grade_spread_robust_zscore",
    "vix_percentile",
    "vix_zscore",
    "vix_robust_zscore",
    "dgs30_percentile",
    "dgs30_zscore",
    "dgs30_robust_zscore",
    "dfii10_percentile",
    "dfii10_zscore",
    "dfii10_robust_zscore",
    "sp500_drawdown_3m_percentile",
    "sp500_drawdown_3m_robust_zscore",
    "nasdaq100_drawdown_3m_percentile",
    "nasdaq100_drawdown_3m_robust_zscore",
    "initial_claims_4w_avg_percentile",
    "initial_claims_4w_avg_robust_zscore",
    "continuing_claims_4w_avg_percentile",
    "continuing_claims_4w_avg_robust_zscore",
}
METRIC_ALIASES = {
    "wti_30d_change": ("wti_oil_30d_change",),
    "brent_30d_change": ("brent_oil_30d_change",),
}
SOURCE_BADGE_ALIASES = {
    "official_api": "official",
    "official_or_public_data_api": "official",
    "public_data_api": "official",
    "third_party_api": "proxy",
    "manual": "local",
    "cached_report": "derived",
}
DGS30_BREAKOUT_MISSING_REASON = "Requires explicit confirmation rule and sufficient DGS30 history."
PORTFOLIO_COMPACT_INTERPRETATION_HINT = (
    "Cash reserve excluded from target mix; portfolio deviation is not "
    "attributed to market factors; reference review only."
)
LABOR_METRIC_SPECS = [
    ("unemployment_rate", "Unemployment rate", "percent", "percent", "missing"),
    ("initial_jobless_claims", "Initial jobless claims", "claims", "number", "missing"),
    ("nonfarm_payrolls", "Nonfarm payrolls", "thousand_persons", "number", "missing"),
    ("continuing_claims", "Continuing claims", "claims", "number", "missing"),
    (
        "unemployment_rate_3m_avg",
        "Unemployment rate 3M average",
        "percent",
        "percent",
        "insufficient_history",
    ),
    (
        "unemployment_rate_12m_low_gap",
        "Unemployment 12M low gap",
        "pp",
        "pp",
        "insufficient_history",
    ),
    ("initial_claims_4w_avg", "Initial claims 4W average", "claims", "number", "insufficient_history"),
    ("continuing_claims_4w_avg", "Continuing claims 4W average", "claims", "number", "insufficient_history"),
    ("sahm_rule_proxy_status", "Sahm rule proxy status", None, "text", "insufficient_history"),
    ("labor_deterioration_status", "Labor deterioration status", None, "text", "insufficient_history"),
]
CORE_METRIC_KEYS = {
    "credit_stress": {"high_yield_spread", "investment_grade_spread", "vix", "credit_stress_status"},
    "rate_pressure": {"dgs2", "dgs10", "dgs30", "dgs30_distance_to_5pct"},
    "real_yield_pressure": {"dfii10", "t10yie", "real_yield_pressure_status"},
    "inflation_energy_pressure": {
        "core_cpi_yoy",
        "core_pce_yoy",
        "ppiaco_yoy",
        "ppi_final_demand",
        "ppi_final_demand_yoy",
        "wti_30d_change",
        "brent_30d_change",
    },
    "equity_trend": {
        "sp500_30d_return",
        "nasdaq100_30d_return",
        "nasdaq_vs_sp500_30d",
    },
    "breadth_concentration_proxy": {
        "spy_proxy_30d_return",
        "rsp_proxy_30d_return",
        "qqq_proxy_30d_return",
        "spy_vs_rsp_30d",
        "qqq_vs_spy_30d",
        "hyg_vs_lqd_30d",
    },
    "market_stress_derived": {
        "sp500_drawdown_3m",
        "nasdaq100_drawdown_3m",
        "dgs10_dgs2_curve_slope",
        "dgs30_dgs10_curve_slope",
        "tlt_vs_shy_30d",
    },
    "portfolio_deviation": {
        "max_deviation_asset",
        "max_deviation_pp",
        "equity_total_deviation_pp",
    },
}
METRIC_SPECS = {
    "credit_stress": [
        ("high_yield_spread", "High-yield spread", "percent", "percent", "missing"),
        ("investment_grade_spread", "Investment-grade spread", "percent", "percent", "missing"),
        ("vix", "VIX", "index", "number", "missing"),
        ("credit_stress_status", "Credit stress status", None, "text", "missing"),
    ],
    "rate_pressure": [
        ("dgs2", "2Y Treasury yield", "percent", "percent", "missing"),
        ("dgs10", "10Y Treasury yield", "percent", "percent", "missing"),
        ("dgs30", "30Y Treasury yield", "percent", "percent", "missing"),
        ("dgs30_distance_to_5pct", "30Y distance to 5%", "pp", "pp", "missing"),
        ("dgs10_5d_avg", "10Y 5D average", "percent", "percent", "insufficient_history"),
        ("dgs30_breakout_confirmed", "30Y breakout confirmed", None, "bool", "research_needed"),
    ],
    "real_yield_pressure": [
        ("dfii10", "10Y real yield", "percent", "percent", "missing"),
        ("t10yie", "10Y breakeven inflation", "percent", "percent", "missing"),
        ("real_yield_pressure_status", "Real yield pressure status", None, "text", "missing"),
    ],
    "inflation_energy_pressure": [
        ("core_cpi_yoy", "Core CPI YoY", "percent", "signed_percent", "missing"),
        ("core_pce_yoy", "Core PCE YoY", "percent", "signed_percent", "missing"),
        ("ppiaco_yoy", "PPIACO YoY", "percent", "signed_percent", "missing"),
        ("ppi_final_demand", "PPI final demand", "index", "number", "missing"),
        ("ppi_final_demand_yoy", "PPI final demand YoY", "percent", "signed_percent", "insufficient_history"),
        ("wti_30d_change", "WTI 30D change", "percent", "signed_percent", "insufficient_history"),
        ("brent_30d_change", "Brent 30D change", "percent", "signed_percent", "insufficient_history"),
    ],
    "equity_trend": [
        ("sp500_30d_return", "S&P 500 30D return", "percent", "signed_percent", "insufficient_history"),
        ("sp500_60d_return", "S&P 500 60D return", "percent", "signed_percent", "insufficient_history"),
        ("nasdaq100_30d_return", "Nasdaq 100 30D return", "percent", "signed_percent", "insufficient_history"),
        ("nasdaq100_60d_return", "Nasdaq 100 60D return", "percent", "signed_percent", "insufficient_history"),
        ("nasdaq_vs_sp500_30d", "Nasdaq vs S&P 500 30D", "pp", "pp", "insufficient_history"),
    ],
    "breadth_concentration_proxy": [
        ("spy_proxy_30d_return", "SPY proxy 30D return", "percent", "signed_percent", "insufficient_history"),
        ("spy_proxy_60d_return", "SPY proxy 60D return", "percent", "signed_percent", "insufficient_history"),
        ("rsp_proxy_30d_return", "RSP proxy 30D return", "percent", "signed_percent", "insufficient_history"),
        ("rsp_proxy_60d_return", "RSP proxy 60D return", "percent", "signed_percent", "insufficient_history"),
        ("qqq_proxy_30d_return", "QQQ proxy 30D return", "percent", "signed_percent", "insufficient_history"),
        ("qqq_proxy_60d_return", "QQQ proxy 60D return", "percent", "signed_percent", "insufficient_history"),
        ("spy_vs_rsp_30d", "SPY vs RSP 30D", "pp", "pp", "insufficient_history"),
        ("spy_vs_rsp_60d", "SPY vs RSP 60D", "pp", "pp", "insufficient_history"),
        ("qqq_vs_spy_30d", "QQQ vs SPY 30D", "pp", "pp", "insufficient_history"),
        ("qqq_vs_spy_60d", "QQQ vs SPY 60D", "pp", "pp", "insufficient_history"),
        ("hyg_vs_lqd_30d", "HYG vs LQD 30D", "pp", "pp", "insufficient_history"),
        ("hyg_vs_lqd_60d", "HYG vs LQD 60D", "pp", "pp", "insufficient_history"),
    ],
    "market_stress_derived": [
        ("sp500_drawdown_3m", "S&P 500 3M drawdown", "percent", "signed_percent", "insufficient_history"),
        ("sp500_drawdown_6m", "S&P 500 6M drawdown", "percent", "signed_percent", "insufficient_history"),
        ("nasdaq100_drawdown_3m", "Nasdaq 100 3M drawdown", "percent", "signed_percent", "insufficient_history"),
        ("nasdaq100_drawdown_6m", "Nasdaq 100 6M drawdown", "percent", "signed_percent", "insufficient_history"),
        ("dgs10_dgs2_curve_slope", "10Y-2Y curve slope", "pp", "pp", "insufficient_history"),
        ("dgs30_dgs10_curve_slope", "30Y-10Y curve slope", "pp", "pp", "insufficient_history"),
        ("tlt_proxy_30d_return", "TLT proxy 30D return", "percent", "signed_percent", "insufficient_history"),
        ("gld_proxy_30d_return", "GLD proxy 30D return", "percent", "signed_percent", "insufficient_history"),
        ("shy_proxy_30d_return", "SHY proxy 30D return", "percent", "signed_percent", "insufficient_history"),
        ("tlt_vs_shy_30d", "TLT vs SHY 30D", "pp", "pp", "insufficient_history"),
    ],
    "portfolio_deviation": [
        ("max_deviation_asset", "Max deviation asset", None, "text", "missing"),
        ("max_deviation_pp", "Max deviation", "pp", "pp", "missing"),
        ("equity_total_deviation_pp", "Equity total deviation", "pp", "pp", "missing"),
        ("cash_reserve_status", "Cash reserve status", None, "text", "missing"),
        ("holdings_updated_at", "Holdings updated at", None, "text", "missing"),
    ],
}
